name: Pull request check
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Lint check
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
